Homework; Lesson 8; Level 7; Task 31,32.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #1036
Opened 2021-03-20 14:15 UTC by aleksaK

2021-03-20 18:34 UTC, konstantins-buts requested changes

2021-03-20 18:34 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_8/level_7/task_31/BooksRepository.java
> +    static private final int length = 10; // размер массива
Статика хорошо работает в утилитарных случаях. Тут полноценный компонент, состояние которого должно быть уникально в рамках каждого из объектов. Соответственно, все свойства и методы класса `Repository` должны быть обычными.

2021-03-20 18:34 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_8/level_7/task_31/BooksRepository.java
> +                index = i;
Думаю тут можно сразу вернуть `array[i]`, соответственно переменная `index` избыточна и условный код снизу тоже, кроме `return null`.

2021-03-20 19:42 UTC, aleksaK commented
Убрал статику, подправил методы.

2021-03-21 12:14 UTC, konstantins-buts approved these changes

2021-03-21 12:15 UTC, merged