Lesson10 Level5 Task13-18
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #1150
Opened 2021-03-29 16:01 UTC by juka2506

2021-04-03 13:40 UTC, konstantins-buts requested changes

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReader.java
> +    boolean addNewBook(Book book);
В названии метода необязательно добавлять что мы хотим добавлять, поскольку этот контекст есть в названии интерфейса или параметре метода. Более того, такие методы нельзя обобщить без переименования.

```java
interface BookReader {
  boolean add(Book book); // По параметру видно, что речь идет про книгу
  boolean delete(Book book);
}
```

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReader.java
> +    String[] findAllBooks();
Стоит ли возвращать массив строк, если в названии метода сказано, что возвращаются книги?
```java
interface BookReader {
    Book[] findAll(); // Находим все книги, которые доступны
}
```

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +    private Book[] books = new Book[1];
С точки зрения кода было бы проще начать с массива 0 размера, тогда нету необходимости добавлять лишние проверки, которые будут отрабатывать каждый раз, даже если массив уже не пустой 🙂

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +        BookValidation bookValidation = new BookValidation();
Если присмотреться, то можно заметить, что класс `BookValidation` является зависимостью для `BookReaderImpl`, поэтому его можно смело передавать через конструктор и не пересоздавать каждый раз при вызове `validate()`.

Тем более, что этот же класс необходим в методах ниже.

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +        return books[0] == null;
При создании массива с 0 длиной эту проверку можно опустить 🙂

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +    private void addNewBookInfoToArray(Book book) {
Как правило, такое действие еще называют просто `push` 😉

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +    private int emptyElementIndex() {
Я бы немного переименовал до `lastEmptyIndex()`, если это действительно ожидаемое поведение.

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +        int emptyElementIndex = 0;
Несуществующий индекс лучше возвращать как `-1`, потому что 0 может быть одновременно корректным, но не пустым индексом.

2021-04-03 13:40 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookValidation.java
> +class BookValidation {
Если бы этот класс был должностью, то как бы его можно было назвать? Например - `BookValidator`

2021-04-05 09:54 UTC, juka2506 commented
исправила

2021-04-06 14:50 UTC, konstantins-buts requested changes

2021-04-06 14:50 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +        BookValidator bookValidator = new BookValidator();
Внедрение зависимости (`BookValidator`) извне все равно нет, потому что на уровне свойства класс сам создает свою зависимость, а код в конструкторе просто избыточен.

В конечном итоге должна быть подобная реализация:
```java
class BookReaderImpl implements BookReader {   
    ...
    private final BookValidator bookValidator;

    public BookReaderImpl(BookValidator bookValidator) {
       this.bookValidator = bookValidator;
     }
    ...
}
```

2021-04-07 09:24 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +        BookValidator bookValidator = new BookValidator();
done

2021-04-11 10:11 UTC, konstantins-buts approved these changes

2021-04-11 10:11 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_10/level_5/BookReaderImpl.java
> +    private BookValidator bookValidator;
Как правило, свойства которые внедряют извне, помечают как `final`.

2021-04-11 10:11 UTC, merged