Homework; Lesson 10; Level 4; Task 12.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #1163
Opened 2021-03-30 18:20 UTC by aleksaK

2021-04-03 14:24 UTC, konstantins-buts requested changes

2021-04-03 14:24 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_10/level_4/task_12/FahrenheitConverter.java
> +    public Optional convert(double celsiusTemperature) {
`Optional` используют в том случае, если есть реальная возможность наткнуться на отсутствующее значение. В случае с расчетами это маловероятно, тут достаточно вернуть результат вычислений

2021-04-03 16:32 UTC, aleksaK commented
Поменял Optional на double! ) Идея с Optional была, что если пользователь запросит конвертировать температуру ниже -273.15C, то не возвращать никакое значение :)

2021-04-06 15:16 UTC, konstantins-buts approved these changes

2021-04-06 15:16 UTC, merged