Homework; Lesson 10; Level 5; Tasks 13,14,15,16,17,18.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #1196
Opened 2021-04-02 19:13 UTC by aleksaK

2021-04-03 14:30 UTC, konstantins-buts requested changes

2021-04-03 14:30 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_10/level_5/task_13/BooksRepository.java
> +    private Book[] repository;
В данном случае лучше сразу создать пустой массив, от которого можно отталкиваться.

2021-04-03 14:30 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_10/level_5/task_13/BooksRepository.java
> +            return true;
Точно ли должно быть `true`, учитывая что книга не может содержаться в массиве, которого нет? 🤔

2021-04-03 14:30 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_10/level_5/task_13/BookReader.java
> +interface BookReader {
В названиях методов можно опускать слова, контект которых можно получить из интерфейса, параметров или возвращаемых типов:
```java
interface BookReader {
    boolean add(Book book); // По параметру видно, что мы хотим добавить книгу
    boolean checkContains(Book book);
}
```

2021-04-03 14:30 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_10/level_5/task_14/BookReader.java
> +    boolean checkParameters(Book book);
Действительно ли это должен быть контрактный метод, или это часть конкретной реализации этого интерфейса, которая может быть спрятана от пользователей?

2021-04-03 17:33 UTC, aleksaK commented
Все исправлено! )

2021-04-06 15:20 UTC, konstantins-buts approved these changes

2021-04-06 15:20 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_10/level_5/task_14/BooksRepository.java
> +        Book[] arr = createArr(count);
Вместо отдельной переменной `count` можно использовать текущий размер массива и прибавить к нему 1. Такие параллельные переменные - это хорошая почва чтобы где-нибудь ошибиться 🙂 
```java
private void save(Book book) {
    Book[] arr = createArr(repository.length + 1);
    ...
}
```

2021-04-06 15:20 UTC, merged