Bogdans Pavlovs - Lesson 3 - Level 7 - Task 31
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #228
Opened 2021-02-07 13:25 UTC by bpavlovs

2021-02-09 16:24 UTC, konstantins-buts requested changes
См. комментарии

2021-02-09 16:24 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_3/level_7/task_31/BankAccountDemo.java
> +        int moneyAmount = bankAccount.getMoney();
> Менять можно только класс BankAccount.

😏

2021-02-09 16:24 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_3/level_7/task_31/BankAccount.java
> +        return this.money;
Подсказка: число можно преобразовать в строку 😉

2021-02-10 08:19 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_3/level_7/task_31/BankAccount.java
> +        return this.money;
Vrode ponjal :D no "+owner" i "+money" v BankAccountDemo zamenitj mozhno? (na moneyAmount i ownerFirstName)?

2021-02-10 15:01 UTC, konstantins-buts approved these changes

2021-02-10 15:01 UTC, merged