Homework; lesson 3; level 5; 18,19,20,21,22 tasks.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #277
Opened 2021-02-08 20:07 UTC by aleksaK

2021-02-09 17:31 UTC, konstantins-buts requested changes

2021-02-09 17:31 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_3/level_5/task_22/Dog.java
> +        colour = "зеленый";
Новый цвет собаки должен передаваться в качестве параметра к методу 🙂

2021-02-18 08:48 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_3/level_5/task_22/Dog.java
> +        colour = "зеленый";
исправил )

2021-02-21 18:04 UTC, konstantins-buts requested changes

2021-02-21 18:04 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_3/level_5/task_22/Dog.java
> +        colour = "зеленый";
Боюсь, что нет. Логика должна выглядеть примерно так:
```java
void changeColor(String color) {
  this.color = color;
}
```

2021-02-21 19:22 UTC, konstantins-buts approved these changes

2021-02-21 19:22 UTC, merged