Level_3 - task_9
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #33
Opened 2021-01-29 19:15 UTC by CoArchie

Homework 👍

2021-01-29 19:23 UTC, konstantins-buts commented on src/main/java/students/arkadij/lesson_2/level_3/task_9/Task_9.java
> +            for (i = 0; i <= 10; i++)
Если уже начали использовать циклы, то желательно использовать его по всем хорошим практикам, а именно - объявлять переменную счетчика в самом заголовке цикла 😉 : 
```java
for (int i = 0; i <= 10; i++) {
  ...
}
```

2021-01-29 19:23 UTC, konstantins-buts requested changes
См. комментарий

2021-01-29 19:43 UTC, CoArchie commented on src/main/java/students/arkadij/lesson_2/level_3/task_9/Task_9.java
> +            for (i = 0; i <= 10; i++)
Как-то не подумал, спасибо учту.

2021-01-30 20:13 UTC, CoArchie commented
Задания закончил, только показалось что их маловато.  Спасибо большое.

2021-01-30 20:28 UTC, konstantins-buts commented on src/main/java/students/arkadij/lesson_2/level_4/Task_13.txt
> +Закончил на этом.
Думаю это связано с тем, что мы используем JDK через Intellij IDEA, а не как полноценную инсталляцию. Отсюда и отсутствие программы в точки зрения Windows. 🤷‍♂️

2021-01-30 20:30 UTC, konstantins-buts commented on src/main/java/students/arkadij/lesson_2/level_7/Task_27.txt
> +Правильные с точки зрения Java кода названия классам:
Тут задача больше сводилась к тому, чтобы корректно преобразовать эти слова в CamelCase в соответствии с схемой наименования классов. 😉

2021-01-30 20:31 UTC, konstantins-buts approved these changes

2021-01-30 20:31 UTC, merged