Bogdans Pavlovs - Lesson 4 - Level 6 - Task 17
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #396
Opened 2021-02-14 11:34 UTC by bpavlovs

2021-02-14 13:59 UTC, konstantins-buts requested changes

2021-02-14 13:59 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_4/level_6/task_17/Stock.java
> +    public void getPriceInformation(){
Согласно условию, этот метод должен вернуть информационную строку:
```java
priceInformation = google.getPriceInformation();
```

2021-02-14 14:00 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_4/level_6/task_17/StockDemo.java
> +        Stock gameStop = new Stock("GME", 5);
🚀 🚀 🚀

2021-02-15 14:32 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_4/level_6/task_17/StockDemo.java
> +        Stock gameStop = new Stock("GME", 5);
💎🙌💎

2021-02-15 14:45 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_4/level_6/task_17/Stock.java
> +    public void getPriceInformation(){
Точно! Вроде исправил :)

2021-02-16 20:31 UTC, konstantins-buts approved these changes

2021-02-16 20:31 UTC, merged