Bogdans Pavlovs - Lesson 4 - Level 7 - Task 24
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #400
Opened 2021-02-14 13:03 UTC by bpavlovs

2021-02-14 14:02 UTC, konstantins-buts requested changes

2021-02-14 14:02 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_4/level_7/task_24/Calculator.java
> +    public void expectedResult1(int result, int expectedResult){
Эти методы не относятся к основный функциям класса `Calculator`. Мы хотим их использовать только в тестах, поэтому им больше подходит `CalculatorTest`.

2021-02-15 14:52 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_4/level_7/task_24/Calculator.java
> +    public void expectedResult1(int result, int expectedResult){
Надеюсь правильно понял, all done

2021-02-16 20:34 UTC, konstantins-buts approved these changes

2021-02-16 20:34 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_4/level_7/task_24/CalculatorTest.java
> +    public void expectedResult1(int result, int expectedResult){
Мы это еще не обсуждали, но мы можем пользоваться т.н. перегрузкой методов (method overloading), когда метод называется одинаково, но параметры у него разные (с точки зрения типов и последовательности):
```java
void expect(int actual, int expected) { ... }
void expect(boolean actual, boolean expected) { ... }
```

2021-02-16 20:34 UTC, merged