Homework, Lesson 4, Level 3, Tasks 8,9,10.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #417
Opened 2021-02-15 16:16 UTC by aleksaK

2021-02-16 21:12 UTC, konstantins-buts requested changes

2021-02-16 21:12 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_3/task_10/IntegerMax.java
> +        if (intFirst > intSecond && intFirst > intThird) {             // 1
Мы можем использовать простые функции, чтобы составлять из них более сложные, например:
`max(a, max(b, c))`

Боюсь представить, какое сложное условие может получиться, если нужно будет найти максимальное число из еще больших переменных. 😅

2021-02-17 11:22 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_4/level_3/task_10/IntegerMax.java
> +        if (intFirst > intSecond && intFirst > intThird) {             // 1
Вроде исправил )))

2021-02-17 15:37 UTC, konstantins-buts requested changes

2021-02-17 15:37 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_3/task_10/IntegerMax.java
> +    public int max1(int intSecond, int intThird) {   // сначала вычисляется Max(b, c)
Достаточно всего лишь одной функции `max`, поскольку они выполняют одно и то же действие. Вторую, дублирующую, можно убрать 😉

2021-02-17 16:35 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_4/level_3/task_10/IntegerMax.java
> +    public int max1(int intSecond, int intThird) {   // сначала вычисляется Max(b, c)
попытка номер три )

2021-02-21 18:04 UTC, konstantins-buts approved these changes

2021-02-21 18:04 UTC, merged