Homework; Lesson 4; Level 4; Tasks 11,12,13,14,15.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #422
Opened 2021-02-15 23:35 UTC by aleksaK

2021-02-16 21:14 UTC, konstantins-buts requested changes

2021-02-16 21:14 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_4/task_13/Calculator.java
> +        if (number % 2 == 0) {
Можно сократить до:
```java
boolean isEven(int number) {
    return number % 2 == 0;
}
```

2021-02-16 21:14 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_4/task_15/Calculator.java
> +        if (firstNumber > secondNumber && firstNumber > thirdNumber) {
Это можно упростить, если использовать метод `maxOfTwoNumbers()` 🙂

2021-02-17 15:13 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_4/level_4/task_15/Calculator.java
> +        if (firstNumber > secondNumber && firstNumber > thirdNumber) {
Исправлено )

2021-02-17 15:42 UTC, konstantins-buts requested changes

2021-02-17 15:42 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_4/task_15/Calculator.java
> +    public int maxOfThreeNumbers1(int x, int thirdNumber) {
Все же, это несовсем то, что я имел в виду. Тебе достаточно создать одну простую функцию (или взять уже готовую) и переиспользовать ее:
```java
class Main {
    public static void main(String[] args) {

        int a = 6;
        int b = 7;
        int c = 8;

        // Краткий вариант
        int max1 = max(a, max(b, c));

        // Длинный вариант
        int temp = max(a, b);
        int max2 = max(temp, c);
    }

    public static int max(int a, int b) {
        if (a > b) {
            return a;
        } else {
            return b;
        }
    }
}
```

Как видишь, функция используется одна и та же. 🙂

2021-02-18 07:40 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_4/level_4/task_15/Calculator.java
> +    public int maxOfThreeNumbers1(int x, int thirdNumber) {
убрал лишний метод. Теперь, надеюсь, правильно. )

2021-02-21 18:05 UTC, konstantins-buts approved these changes

2021-02-21 18:05 UTC, merged