lesson4-level7-22Task
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #425
Opened 2021-02-16 08:37 UTC by KristinePaskevica

2021-02-16 20:53 UTC, konstantins-buts requested changes

2021-02-16 20:53 UTC, konstantins-buts commented on src/main/java/students/kristine_paskevica/lesson_4/level_7/FizzBuzz.java
> +         if (number % 3 == 0 && number !=0){
Дополнительная проверка `number != 0` избыточна, думаю оно будет отлично работать и без этого 🙂

2021-02-16 20:53 UTC, konstantins-buts commented on src/main/java/students/kristine_paskevica/lesson_4/level_7/FizzBuzz.java
> +         else if (number % 3 == 0 && number % 5 == 0 && number != 0){
Это условие должно быть самым первым, иначе предыдущие его будут перекрывать, т.е. если `number % 3 == 0` сработает, то до `number % 3 == 0 && number % 5 == 0` код не дойдет. Наиболее строгие выражения должны быть выше.

2021-02-16 20:53 UTC, konstantins-buts commented on src/main/java/students/kristine_paskevica/lesson_4/level_7/FizzBuzzTest.java
> +             if (rezultParbaude == realRezult) {
Для того, чтобы сравнивать строки по содержимому (значению), нужно использовать метод `.equals()`, например: `"text".equals("text") // true`

2021-02-22 12:00 UTC, KristinePaskevica commented on src/main/java/students/kristine_paskevica/lesson_4/level_7/FizzBuzz.java
> +         if (number % 3 == 0 && number !=0){
OK

2021-02-22 12:00 UTC, KristinePaskevica commented on src/main/java/students/kristine_paskevica/lesson_4/level_7/FizzBuzz.java
> +         else if (number % 3 == 0 && number % 5 == 0 && number != 0){
Sapratu, apmainīju vietām

2021-02-22 12:05 UTC, KristinePaskevica commented on src/main/java/students/kristine_paskevica/lesson_4/level_7/FizzBuzzTest.java
> +             if (rezultParbaude == realRezult) {
Izlaboju

2021-02-23 15:39 UTC, konstantins-buts approved these changes

2021-02-23 15:39 UTC, merged