Homework; Lesson 4; Level 6; Task 17.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #429
Opened 2021-02-16 11:24 UTC by aleksaK

2021-02-16 21:17 UTC, konstantins-buts requested changes

2021-02-16 21:17 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_6/task_17/Stock.java
> +        return currentPrice;
Этот метод ничего не изменяет, а возвращает. Он должен принимать новую стоимость, и автоматически изменять текущую, максимальную и минимальную стоимость. Соответственно, методы `setMaxPrice()` и `setMinPrice()` не нужны.

2021-02-17 13:56 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_4/level_6/task_17/Stock.java
> +        return currentPrice;
Исправлено! )

2021-02-17 15:45 UTC, konstantins-buts requested changes

2021-02-17 15:45 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_6/task_17/Stock.java
> +    int updatePrice() {
Уже ближе 🙂 Я писал, что метод принимает новую стоимость в качестве параметра и на основе этого обновляет данные по этой акции:
```java
void updatePrice(int price) {
  // TODO
}
```

Более того, в данном случае возвращать какой-либо результат не имеет смысла, потому что у нас нету четкого регламента что именно возвращать. Новая стоимость извества, потому что ее передают в качестве параметра. Минимальная или максимальная стоимость? Как тогда понять, что изменилось?

2021-02-18 08:41 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_4/level_6/task_17/Stock.java
> +    int updatePrice() {
сделано )

2021-02-21 18:06 UTC, konstantins-buts requested changes

2021-02-21 18:06 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_6/task_17/Stock.java
> +    int finalCurrentPrice;
Это поле избыточно, для работы с текущей ценой нам достаточно одной переменной: `currentPrince` 😉

2021-02-21 18:06 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_4/level_6/task_17/Stock.java
> +        finalCurrentPrice = currentPrice;
Это можно упростить до: `this.currentPrice = currentPrice;`

2021-02-21 18:27 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_4/level_6/task_17/Stock.java
> +        finalCurrentPrice = currentPrice;
Убрал лишнюю переменную.

2021-02-21 19:21 UTC, konstantins-buts approved these changes
👍

2021-02-21 19:22 UTC, merged