Lesson5 Level4 Task27
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #496
Opened 2021-02-18 11:31 UTC by juka2506

2021-02-23 15:46 UTC, konstantins-buts requested changes

2021-02-23 15:46 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_5/level_4/task_27/Task27.java
> +        System.out.println(Arrays.stream(numbers).max().getAsInt()); // найдите наибольшее число в массиве и выведети его на консоль
Воу-воу, мы пока такие вещи не проходили :) Как на счет решения на циклах?

2021-02-23 15:50 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_5/level_4/task_27/Task27.java
> +        System.out.println(Arrays.stream(numbers).max().getAsInt()); // найдите наибольшее число в массиве и выведети его на консоль
прогуглила и нашла решение в одну строчку. так нельзя?))

2021-02-23 16:44 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_5/level_4/task_27/Task27.java
> +        System.out.println(Arrays.stream(numbers).max().getAsInt()); // найдите наибольшее число в массиве и выведети его на консоль
Можно (и даже нужно), но пока что мы будем последовательны 😏

2021-02-23 16:45 UTC, konstantins-buts requested changes

2021-02-23 16:45 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_5/level_4/task_27/Task27.java
> +        int max = 0;
А если массив состоит из отрицательных чисел, будет ли это работать? 🙂

2021-02-23 16:56 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_5/level_4/task_27/Task27.java
> +        int max = 0;
поняла ошибку уже в ходе исправления следующего задания )

2021-02-26 16:31 UTC, konstantins-buts approved these changes

2021-02-26 16:31 UTC, merged