Lesson5 Level6 Task36
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #529
Opened 2021-02-18 15:57 UTC by juka2506

2021-02-23 15:53 UTC, konstantins-buts requested changes

2021-02-23 15:53 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_5/level_6/task_36/Arrays.java
> +        return java.util.Arrays.stream(array).max().getAsInt();
На циклах 😉

2021-02-23 15:53 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_5/level_6/task_36/ArraysTest.java
> +    public void shouldFindMaxNumber() {
Можно также рассмотреть другие сценарий, например, что если все элементы массива имеют одинавокое значение? Что если первый или последний элемент максимальные?

2021-02-23 16:48 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_5/level_6/task_36/Arrays.java
> +        return java.util.Arrays.stream(array).max().getAsInt();
Исправила

2021-02-23 16:49 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_5/level_6/task_36/ArraysTest.java
> +    public void shouldFindMaxNumber() {
Добавила тесты и на эти случаи, все работает нормально :) всегда надо столько тестов писать в дз?

2021-02-26 16:33 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_5/level_6/task_36/ArraysTest.java
> +    public void shouldFindMaxNumber() {
Это было как размышление 😉 😄

2021-02-26 16:33 UTC, konstantins-buts approved these changes

2021-02-26 16:33 UTC, merged