lesson5-level2-AllTask
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #584
Opened 2021-02-20 18:59 UTC by KristinePaskevica

2021-02-21 19:51 UTC, konstantins-buts requested changes

2021-02-21 19:51 UTC, konstantins-buts commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task13.java
> +             sum = sum + masivs[i];
Можно воспользоваться сокращенной формой: `sum += masivs[i];`

2021-02-21 19:51 UTC, konstantins-buts commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task14.java
> +         for (int i = 0; i < 3; i++) {
Удобнее использовать свойство с размером массива:
```java
for (int i = 0; i < masivs.length; i++) { ... }
```

Это же касается и случая с рассчетом среднего арифметического. В случае, если размер массива будет изменен, нам нужно вносить правки в 2х местах, чтобы программа работала корректно. Когда код больше, то упустить это из виду значительно проще. 😉

2021-02-21 19:51 UTC, konstantins-buts commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task15.java
> +            masivs[i]=masivs[i]*2;
Увеличить **на** 2 предполагает сложение, а не умножение 🤓 😉

2021-02-21 19:51 UTC, konstantins-buts commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task15.java
> +        for(int i = 0; i< 3;i++){
Предлагаю все же ссылаться на свойство с размером массива

2021-02-22 17:12 UTC, KristinePaskevica commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task13.java
> +             sum = sum + masivs[i];
Sapratu, izlaboju

2021-02-22 17:29 UTC, KristinePaskevica commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task14.java
> +         for (int i = 0; i < 3; i++) {
izlaboju

2021-02-22 17:30 UTC, KristinePaskevica commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task15.java
> +            masivs[i]=masivs[i]*2;
Laikam bija prāta aptumsums! Izlabots

2021-02-22 17:31 UTC, KristinePaskevica commented on src/main/java/students/kristine_paskevica/lesson_5/level_2/Task15.java
> +        for(int i = 0; i< 3;i++){
Izlabots

2021-02-23 15:43 UTC, konstantins-buts approved these changes

2021-02-23 15:43 UTC, merged