Bogdans Pavlovs - Lesson 5 - Level 2 - Tasks 10 to 15
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #586
Opened 2021-02-21 09:21 UTC by bpavlovs

2021-02-21 19:53 UTC, konstantins-buts requested changes

2021-02-21 19:53 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_5/level_2/task_10/ArraysTask10.java
> +        System.out.println(numbers[0]);
Не забудь, что у нас есть массивы 🙂

2021-02-22 22:20 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_5/level_2/task_10/ArraysTask10.java
> +        System.out.println(numbers[0]);
Понял, вроде все таски поправил :)

2021-02-23 15:43 UTC, konstantins-buts approved these changes

2021-02-23 15:43 UTC, merged