Lesson6 Level3 Task16
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #669
Opened 2021-02-26 12:15 UTC by juka2506

Не уверена, что в тестах методы написаны лучшим образом, но не придумала, как по-другому протестировать void метод.
По крайне мере, все работает

2021-02-27 13:10 UTC, konstantins-buts requested changes

2021-02-27 13:10 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_6/level_3/task_16/ArrayServiceTest.java
> +        String realResult = Arrays.toString(arr);
Мы пока такие нюансы не разбирали, но тестируется очень просто: содержимое массива `arr` будет изменено после вызова метода `revert` (больше на `reverse` похоже 🤔 ).  В рамках теста создаешь массив, только в обратном порядке и сравниваешь:
```java
int[] arr = {1, 2, 3};
int[] exp = {3, 2, 1};

arrayService.revert(arr);
Arrays.equals(arr, expected);
```
Проверять строки можно, но это очень неэффективно 🙂

2021-03-03 08:02 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_6/level_3/task_16/ArrayServiceTest.java
> +        String realResult = Arrays.toString(arr);
done 👍

2021-03-07 10:34 UTC, konstantins-buts approved these changes

2021-03-07 10:34 UTC, merged