Lesson6 Level4 Task21
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #678
Opened 2021-02-26 16:24 UTC by juka2506

Возможно, не самая лучшая реализация, но парилась с доступом к переменным из методов. Буду рада комментариям и советам по улучшению кода :)

2021-02-27 13:18 UTC, konstantins-buts requested changes

2021-02-27 13:18 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +    public int action (int[][] numbers, int sum) {
Думаю это стоит разделить на два отдельных метода: один только для заполнение массива случайными числами, а другой только на подсчет суммы, например:
```java
public void fill(int[][] array) {
    Random random = new Random();
    for (int i = 0; i < array.length; i++) {
        for (int j = 0; j < array[i].length; j++) {
            array[i][j] = random.nextInt(10);
        }
    }
}

public int sum(int[][] array) {
    int sum = 0;
    for (int[] row : array) {
        for (int col : row) {
            sum += col;
        }
    }
    return sum;
}
```

2021-03-03 08:12 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +    public int action (int[][] numbers, int sum) {
исправила, но строчек то кода больше ))
и  for (int i = 0; i < array.length; i++) {
        for (int j = 0; j < array[i].length; j++) {
эти две строчки полностью повторяются в обоих методах

2021-03-07 10:35 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +    public int action (int[][] numbers, int sum) {
Количество строчек не всегда единственная численная метрика, на которую можно опираться. Хорошая организация кода всегда будет перевешивать объем. 😉

2021-03-07 10:35 UTC, konstantins-buts approved these changes

2021-03-07 10:36 UTC, merged