Lesson6 Level5 Task23
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #690
Opened 2021-02-27 15:11 UTC by juka2506

2021-03-02 16:31 UTC, konstantins-buts requested changes

2021-03-02 16:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_6/level_5/task_23/TicTacToe.java
> +        TicTacToe ticTacToe = new TicTacToe();
В рамках класса к методам можно обращаться без объекта. В тестах такой подход, чтобы каждый сценарий был, можно сказать, с чистого листа. 🙂

2021-03-03 08:15 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_6/level_5/task_23/TicTacToe.java
> +        TicTacToe ticTacToe = new TicTacToe();
а разве в основе ООП не лежит, что мы обращаемся к методу через объект?
экземпляр класса удалила

2021-03-07 10:36 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_6/level_5/task_23/TicTacToe.java
> +        TicTacToe ticTacToe = new TicTacToe();
Верно, мы и в данном случае обращаемся через объект - `this`, т.е. через самого себя.

2021-03-07 10:37 UTC, konstantins-buts approved these changes

2021-03-07 10:37 UTC, merged