Lesson6 Level5 Task24
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #698
Opened 2021-02-28 09:13 UTC by juka2506

2021-03-02 16:32 UTC, konstantins-buts requested changes

2021-03-02 16:32 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_6/level_5/task_24/TicTacToe.java
> +        TicTacToe ticTacToe = new TicTacToe();
В рамках класса к методам можно обращаться без объекта.

2021-03-03 08:18 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_6/level_5/task_24/TicTacToe.java
> +        TicTacToe ticTacToe = new TicTacToe();
done

2021-03-07 10:37 UTC, konstantins-buts approved these changes

2021-03-07 10:37 UTC, merged