Bogdans Pavlovs - Lesson 6 - Level 2 - Tasks 7 to 11
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #703
Opened 2021-02-28 10:25 UTC by bpavlovs

2021-03-02 16:47 UTC, konstantins-buts requested changes

2021-03-02 16:47 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_6/level_2/DayOfTheWeekDetector.java
> +        switch (dayNumber) {
В данном случае лучше сразу возвращать результат, без промежуточных переменных.

2021-03-02 20:26 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_6/level_2/DayOfTheWeekDetector.java
> +        switch (dayNumber) {
![image](https://user-images.githubusercontent.com/74678476/109710193-a7c94700-7b9d-11eb-9345-225063191327.png)

Вроде поправил, я правильно понимаю что точка с запятой в конце принадлежат "return"? по другому не идет :D

2021-03-07 11:25 UTC, konstantins-buts approved these changes

2021-03-07 11:25 UTC, merged