Bogdans Pavlovs - Lesson 6 - Level 4 - Tasks 18 to 21
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #712
Opened 2021-02-28 12:26 UTC by bpavlovs

2021-03-02 16:48 UTC, konstantins-buts requested changes

2021-03-02 16:48 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +            array[i][i] = fillArray.nextInt();
Заполнится ли весь массив или только диагональ?

2021-03-02 16:48 UTC, konstantins-buts commented on src/main/java/students/bogdans_pavlovs/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +            sum += array[i][i];
Посчитается ли вся сумма чисел в массиве или только диагональ?

2021-03-02 20:34 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +            array[i][i] = fillArray.nextInt();
диагональ 😢

2021-03-02 20:34 UTC, bpavlovs commented on src/main/java/students/bogdans_pavlovs/lesson_6/level_4/task_21/TwoDimensionalArray.java
> +            sum += array[i][i];
диагональ 😢

2021-03-07 11:26 UTC, konstantins-buts approved these changes

2021-03-07 11:26 UTC, merged