Homework; Lesson 6; Level 3; Tasks 12,13,14,15,16,17.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #729
Opened 2021-02-28 18:02 UTC by aleksaK

2021-03-02 16:53 UTC, konstantins-buts requested changes

2021-03-02 16:53 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_12/ArrayService.java
> +    boolean containInteger;
Эта переменная избыточна, результат можно вернуть и без нее.

2021-03-02 16:53 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_13/ArrayService.java
> +        for (int i = 0; i < array.length; i++) {
Какой будет результат работы, если я попрошу сосчитать кол-во совпадений несколько раз подряд? 
```java
ArrayService service = new ArrayService();
service.countOccurences(new int[] {1, 2, 3, 2, 3}, 3);
service.countOccurences(new int[] {1, 2, 3, 2, 3}, 3);
service.countOccurences(new int[] {1, 2, 3, 2, 3}, 3);
```

2021-03-02 16:53 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_14/ArrayService.java
> +    boolean replaced;
Какой будет результат работы, если я попрошу заменить один массив одним числом несколько раз подряд?

2021-03-02 16:53 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_15/ArrayService.java
> +    boolean replaced;
🙂

2021-03-02 16:53 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_16/ArrayService.java
> +            array[i] = result[i];
Изменится ли оригинальный массив в таком случае? 🤔

2021-03-02 18:27 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_12/ArrayService.java
> +    boolean containInteger;
убрал лишнюю переменную

2021-03-02 18:30 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_13/ArrayService.java
> +        for (int i = 0; i < array.length; i++) {
Убрал переменную экземпляра, сделал локальную переменную в методе.

2021-03-02 18:33 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_6/level_3/task_16/ArrayService.java
> +            array[i] = result[i];
Хмм...не могу найти здесь ошибку. Вроде оригинальный массив array выдает в конце новые, правильные значения. В методе создавал промежуточный массив result для последующего переноса измененных значений в массив array.

2021-03-07 11:44 UTC, konstantins-buts approved these changes

2021-03-07 11:44 UTC, merged