Lesson 4 homework..
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #785
Opened 2021-03-06 20:20 UTC by iiiLOLAiii

Ooops 🤣

2021-03-07 17:56 UTC, konstantins-buts requested changes

2021-03-07 17:56 UTC, konstantins-buts commented on src/main/java/students/lolita_polakova/lesson_4/level_3/task_8/EqualOrNot.java
> +        } else if (a != b && b != c) {
А если `a == c`? 🤔

2021-03-07 17:56 UTC, konstantins-buts commented on src/main/java/students/lolita_polakova/lesson_4/level_6/task_17/Stock.java
> +    public void getPriceInformation() {
В условии сказано, что эту строку нужно возвращать как результат 🙂

2021-03-07 18:10 UTC, iiiLOLAiii commented on src/main/java/students/lolita_polakova/lesson_4/level_6/task_17/Stock.java
> +    public void getPriceInformation() {
То есть?Оо

2021-03-09 16:55 UTC, konstantins-buts approved these changes

2021-03-09 16:55 UTC, merged