Lesson7 Level7 Task16
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #824
Opened 2021-03-10 12:28 UTC by juka2506

Не было четкого представление как все должно выглядеть  - местами импровизировала
Возможно, все не совсем так должно быть, но по крайне мерее версия рабочая. Все методы тестами проверила. 
Буду ждать комментариев :)

2021-03-13 13:31 UTC, konstantins-buts requested changes
Решение интересное, но можно было ограничиться простым сохранением `UserEntity` в одномерном массиве 😄.

Если продолжать развивать решение в этом же направлении, то стоит скрыть логику работы, больше использовать `UserEntity` как параметр вместо индивидуальных значений и сделать преобразование из массива в объект в одном месте, чтобы логику переиспользовать во всех остальных методах.

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +    String[][] users = new String[1][userEntity.getNumberOfColumns()];
Мы хотим сделать так, чтобы механизм хранения был скрыт от других компонент, которые используют репозиторий. Таким образом мы расслабим связку между ними и при необходимости заменять один репозиторий на другой, например с массива на список или настоящую базу данных, будет проще.

Сейчас эта жесткая связь видна по сигнатуре метода `addNewUser()`, где одним из параметров является массив для хранения пользователей.

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +    public void addNewUser(String[][] users, String id, String name, String surname, String personalCode) {
В данном случае метод может принимать не каждое поле отдельно, а сразу `UserEntity`, например:
```java
public void save(UserEntity user) {
    if (isItFirstUser()) {
        addFirstUser(users, user.getId(), user.getName(), user.getSurname(), user.getPersonalCode());
    } else {
        addOneMoreUser(users, user.getId(), user.getName(), user.getSurname(), user.getPersonalCode());
    }
}
```

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +        int column = 0;
Такие вещи желательно выносить в константы на уровне класса:
```java
class UserEntityRepository {

    private final int COL_IDX_ID = 0;
    private final int COL_IDX_NAME = 1;
    private final int COL_IDX_SURNAME = 2;
    private final int COL_IDX_CODE = 3;

    ...
}
```

Тогда мы можем избавиться от загадочности и лишних математических операций:
```java
private void addNewUserInfoInLastArrayRow(String id, String name, String surname, String personalCode) {
    users[(users.length - 1)][COL_IDX_ID] = id;
    users[(users.length - 1)][COL_IDX_NAME] = name;
    users[(users.length - 1)][COL_IDX_SURNAME] = surname;
    users[(users.length - 1)][COL_IDX_CODE] = personalCode;
}
```

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntity.java
> +        return getClass().getDeclaredFields().length;
Интересный подход, но динамика здесь и статичность в репозитории могут привести к неожиданным ошибкам. Например, тут добавится новое поле, а в репозитории у тебя обработка по прежнему работает только для 4х свойств.

Чтобы немного сгладить этот момент, возможно вынести это значение в константу на уровне репозитория было бы более правильно, тогда у тебя контроль в одном месте.

```java
class UserEntityRepository {
    ...
    private final int COLUMN_COUNT = 4;
    ...
}
```

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +    UserEntity userEntity = new UserEntity("", "", "", "");
Как написал выше, использовать этот объект только ради размера колонок может быть не самой лучшей идеей и желательно это заменить на константу.

Подходящий сценарий для этого класса - передавать его в качестве параметра для манипуляции репозиторием - сохранить пользователя, обновить и т.п., вместо передачи параметров индивидуально.

Это формирует некий контракт для взаимодействия.

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +        return this.users[0][0] == null;
Эту логику можно убрать, если сделать массив пустым с самого начала и каждый раз увеличивать его размер на 1 перед тем как добавить новую запись. 🙂

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +        for (int i = 0; i < (users.length); i++) { //make array copy with all data
Так и быть, можешь использовать `Arrays.copy()` или `System.arraycopy()` 😏

2021-03-13 13:31 UTC, konstantins-buts commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +        return users[i];
Тут потенциально может быть ошибка с выходом за пределы массива. Не самый лучший вариант, но (пока) можно упростить:
```java
private String[] findRowById(String id) {
    for (String[] user : users) { // перебор строк
        if (user[COL_IDX_ID].equals(id)) {
            return user;
        }
    }
    return null;
}
```

2021-04-07 09:29 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +        users[(users.length - 1)][column++] = id;
я пробовала много вариантов и перечитала много информации перед тем как прийти к этому решению.
мне было легче это представлять как двумерный массив из-за ассоциаций с таличкой в эксееле, поэтому так и делала

2021-04-07 10:10 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +        int column = 0;
а как же элемент загадочности? :D

2021-04-07 10:14 UTC, juka2506 commented on src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java
> +        for (int i = 0; i < (users.length); i++) { //make array copy with all data
уже поздно))

2021-04-11 10:09 UTC, konstantins-buts approved these changes

2021-04-11 10:09 UTC, merged