Homework; Lesson 7; Level 7; Tasks 13,15,16.
konstantins-buts/jg-java-1-online-winter-january-wednesday-2021 pull request #861
Opened 2021-03-11 16:35 UTC by aleksaK

2021-03-13 13:47 UTC, konstantins-buts requested changes

2021-03-13 13:47 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_7/level_7/task_16/UserEntity.java
> +class UserEntity {
Класс `UserEntity` представляет собой просто объект с информацией. Как правило, репозиторий это отдельный класс, который инкапсулирует в себе логику хранения объектов `UserEntity` в массиве, списке или реальной базе, т.е. это некая прослойка.

Вынеси часть логики по сохранению, удалению, обновлению и т.п. в отдельный UserRepository класс.

2021-03-13 14:34 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_7/level_7/task_16/UserEntity.java
> +class UserEntity {
Перенес

2021-03-14 21:33 UTC, konstantins-buts requested changes

2021-03-14 21:33 UTC, konstantins-buts commented on src/main/java/students/alex_kalashnikov/lesson_7/level_7/task_16/UserRepository.java
> +    String[][] createArray(int expectedClientAmount, int amountOfClientParameters) {
Репозиторий уже имеет скрытый внутри себя массив пользователей, соответственно снаружи передавать этот массив не нужно, достаточно представить список поддерживаемых операций независимо от механизма хранения:
```java
class UserRepository {

  private UserEntity[] array = new UserEntity[0]; // Например, "увеличивать" массив каждый раз при добавлении нового пользователя

  void save(UserEntity entity) { ... }
  UserEntity findById(String id) { ... } // Такой же стиль для поиска всех пользователей или по имени
  void delete(String id) { ... }

}
```

Это нужно для того, чтобы мы могли более гибко менять реализацию не прибегая к большим изменениям в коде, где используется репозиторий.

2021-03-16 01:32 UTC, aleksaK commented on src/main/java/students/alex_kalashnikov/lesson_7/level_7/task_16/UserRepository.java
> +    String[][] createArray(int expectedClientAmount, int amountOfClientParameters) {
вроде получилось )

2021-03-18 20:53 UTC, konstantins-buts approved these changes

2021-03-18 20:53 UTC, merged